### PR TITLE
fix: Mejorar compatibilidad con Minecraft 1.21.11 y Bedrock

### PR DESCRIPTION
**Pull request by Anonimus1221**
- Mejorar manejo de excepciones de Brigadier (ExceptionInInitializerError)
- Agregar soporte para NoClassDefFoundError en adapters de Paper
- Incluir submódulos de idiomas y mappings
- Garantizar que el plugin se cargue correctamente en Paper/Spigot 1.21.11

FIXES:
- Resolver error de locale no encontrado
- Manejar gracefully excepciones de TagKey.location()
- Soportar casos donde ResourceLocation no está disponible

### CODE REVIEW

**Comment by rtm516** [comment]
We have already started work on supporting 1.21.11 and will merge that into master when finished.
