### ISSUE TITLE
Geyser crashes on Paper 1.16.5

### ISSUE THREAD

**Issue by pavog** [GeyserMC/Geyser#5132]
### Describe the bug

I created a new server with Paper 1.16.5 running on Java 18.
On the [wiki](https://geysermc.org/wiki/geyser/supported-versions/) it tells me that Geyser should work on 1.16.5, but I need ViaVersion. I installed ViaVersion and started the server.
The Geyser plugin does not load and throws the error message:
```
[Server thread/ERROR]: Could not pass event ServerLoadEvent to Geyser-Spigot v2.5.0-SNAPSHOT
java.lang.NoSuchMethodError: 'java.lang.Object com.google.gson.Gson.fromJson(java.io.Reader, com.google.gson.reflect.TypeToken)'
```

Here is the full log: https://mclo.gs/NfEJkbi

### To Reproduce

1. Install Paper 1.16.5
2. Install the latest version of ViaVersion (5.1.2-SNAPSHOT build 611)
3. Install the latest version of Geyser (2.5.0 build 707)
4. Start the server

### Expected behaviour

It should not crash ;-)

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/90b52fc2-a24a-4187-b488-479932fb0b9a)

### Server Version and Plugins

`This server is running Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)`

### Geyser Dump

https://dump.geysermc.org/3OxfxFQpFXGKp3DgRMAYLlD8LxCHib3S

### Geyser Version

2.5.0 build 707

### Minecraft: Bedrock Edition Device/Version

All I guess?

**Comment by UltraHispeed-Elite** [comment]
Try using the Main Geyser Proxy or Viaproxy and its geyser plugin rather than the Spigot Plugin. I think the issue is how outdated the actual Paper version is, so I'm not sure what Geyser has in terms of interacting with the Viaversion plugin.
