### ISSUE TITLE
Doesn't work on Paper 1.17.1

### ISSUE THREAD

**Issue by Guigui20000** [GeyserMC/Geyser#5776]
### Describe the bug

Hey ! I'm not fluent in english sorry. Geyser hasn't worked since the 1.20.100 support version or a previous version (I don't know exactly anymore). The plugin worked perfectly for several years but when I uptdated this, it stopped working and my bedrock players couldn't join my server. There is also an error in the console. I point out that my Minecraft server is running with the latest version of Paper for 1.17.1 version (build 411). I also tested on another server with only Geyser, Floodgate and viaversion and the same issue happened. However, I noticed that the versions from 1.20.1 worked. So, I think that there is a problem with the api version or something like that. 

Error: 
[22:09:58 ERROR]: Could not pass event ServerLoadEvent to Geyser-Spigot v2.8.3-SNAPSHOT
java.lang.NoSuchMethodError: 'boolean io.netty.channel.epoll.Epoll.isTcpFastOpenServerSideAvailable()'
at org.geysermc.mcprotocollib.network.helper.TransportHelper.determineTransportMethod(TransportHelper.java:86) ~[Geyser-Spigot.jar:?]
at org.geysermc.mcprotocollib.network.helper.TransportHelper.<clinit>(TransportHelper.java:36) ~[Geyser-Spigot.jar:?]
at org.geysermc.geyser.network.netty.GeyserServer.<clinit>(GeyserServer.java:90) ~[Geyser-Spigot.jar:?]
at org.geysermc.geyser.GeyserImpl.startInstance(GeyserImpl.java:440) ~[Geyser-Spigot.jar:?]
at org.geysermc.geyser.GeyserImpl.initialize(GeyserImpl.java:272) ~[Geyser-Spigot.jar:?]
at org.geysermc.geyser.GeyserImpl.start(GeyserImpl.java:825) ~[Geyser-Spigot.jar:?]
at org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin.onGeyserEnable(GeyserSpigotPlugin.java:236) ~[Geyser-Spigot.jar:?]
at org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin$1.onServerLoaded(GeyserSpigotPlugin.java:220) ~[Geyser-Spigot.jar:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.17.1.jar:git-Paper-411]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-411]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-411]
at com.heretere.hpwp.listener.HPWPRegisteredListener.callEvent(HPWPRegisteredListener.java:54) ~[HPWP.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-411]
at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:734) ~[patched_1.17.1.jar:git-Paper-411]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-411]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-411]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
at java.lang.Thread.run(Thread.java:840) ~[?:?]

### To Reproduce

1. Have a Minecraft server with the latest build of Paper for the 1.17.1 version (build 411)
2. Install Geyser, Floodgate and viaversion
3. Restart the server

### Expected behaviour

I just wish this error would go away and my bedrock players could join my server

### Geyser Version

Geyser-Spigot v2.8.3-SNAPSHOT

**Comment by Camotoy** [comment]
Seeing as 1.17.1 is rather old, I'm not sure if this will be fixed. You have two options:

- Start your server with the system property `-Dio.netty.transport.noNative=true`. This will fix this issue, but you may have slower network performance on both the Java and Bedrock end.
- Use Geyser-Standalone. Floodgate will still work; there's just some additional setup process.

**Comment by xiaoni0v0** [comment]
It seems that this bug only appears on Linux. The same problem occurred on my Linux server but vanished on my Windows10 computer. I supposed that it relates to the different network behavior on different os.

**Comment by riqvip** [comment]
> It seems that this bug only appears on Linux. The same problem occurred on my Linux server but vanished on my Windows10 computer. I supposed that it relates to the different network behavior on different os.

I'm running into the same problem on a 1.16.5 server on Linux, so this is very likely. However, when I did `-Dio.netty.transport.noNative=true` as Camotoy suggested, it started working perfectly fine. And so far I haven't really noticed an impact on network performance.
