### PR TITLE
Feature/bedrock compatibility 1.21.11

### PR DESCRIPTION
**Pull request by Anonimus1221**
Changes

- Enhanced Brigadier error handling (ExceptionInInitializerError / NoClassDefFoundError)
- Improved Paper adapter compatibility for 1.21.11
- Included language & mappings submodules for full locale support
- Added fallback handling for missing NMS ResourceLocation

Fixes

- Fixed *English locale not found* by initializing submodules correctly
- Prevented crashes from incompatible TagKey.location() calls
- Added debug logs for adapter incompatibility detection

### CODE REVIEW

**Comment by Novampr** [comment]
#6040 is already open, we're working on 1.21.11 support.
